# Generated by Django 5.2.16 on 2026-07-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('id_acceso__gte', 1000), ('id_acceso__lte', 9999)), name='cliente_id_acceso_en_rango'),
        ),
    ]
