# Generated by Django 5.2.16 on 2026-07-20 23:04

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import gestion.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_cliente_id_acceso_en_rango'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('mensualidad_base', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('inscripcion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[gestion.models.validar_inscripcion])),
                ('reajuste_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[gestion.models.validar_reajuste_inicial])),
                ('mora', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('otros_ajustes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('metodo_pago', models.CharField(blank=True, max_length=30)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='dia_pago',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Día 1'), (15, 'Día 15')], default=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscripcion_aplicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reajuste_inicial_aplicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_tarifa',
            field=models.CharField(choices=[('general', 'General'), ('estudiante', 'Estudiante')], default='general', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_tarifa__in', ['general', 'estudiante'])), name='cliente_tipo_tarifa_valido'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('dia_pago__in', [1, 15])), name='cliente_dia_pago_valido'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='gestion.cliente'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('periodo_fin__gte', models.F('periodo_inicio'))), name='pago_periodo_valido'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('reajuste_inicial__in', [Decimal('-50'), Decimal('0'), Decimal('50')])), name='pago_reajuste_inicial_valido'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('inscripcion__in', [Decimal('0'), Decimal('50')])), name='pago_inscripcion_valida'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('mora__gte', Decimal('0'))), name='pago_mora_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('total_pagado', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('mensualidad_base'), '+', models.F('inscripcion')), '+', models.F('reajuste_inicial')), '+', models.F('mora')), '+', models.F('otros_ajustes')))), name='pago_total_pagado_coincide_con_conceptos'),
        ),
    ]
