# Generated by Django 5.2.16 on 2026-07-27 18:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_pago_cliente_dia_pago_cliente_inscripcion_aplicada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estado_membresia', models.CharField(choices=[('vigente', 'Vigente'), ('por_vencer', 'Por vencer'), ('en_gracia', 'En gracia'), ('vencida_con_mora', 'Vencida con mora'), ('sin_pagos', 'Sin pagos')], max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('mora_al_ingresar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('origen', models.CharField(choices=[('cliente', 'Cliente'), ('manual', 'Manual')], default='cliente', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='gestion.cliente')),
            ],
            options={
                'ordering': ['-fecha_hora'],
                'constraints': [models.CheckConstraint(condition=models.Q(('mora_al_ingresar__gte', Decimal('0'))), name='asistencia_mora_no_negativa'), models.CheckConstraint(condition=models.Q(('estado_membresia__in', ['vigente', 'por_vencer', 'en_gracia', 'vencida_con_mora', 'sin_pagos'])), name='asistencia_estado_membresia_valido'), models.CheckConstraint(condition=models.Q(('origen__in', ['cliente', 'manual'])), name='asistencia_origen_valido')],
            },
        ),
    ]
